name: badlands-workshop
channels:
  - conda-forge
  - geo-down-under
dependencies:
  - python=3.8
  - jupyterlab=2.1
  - numpy
  - pip
  - pandas
  - scipy
  - compilers
  - gfortran
  - scikit-image
  - scikit-learn=0.23
  - h5py
  - cmocean
  - shapely
  - cartopy
  - pillow
  - pip:
      - matplotlib==3.3.4
      - gFlex
      - badlands
      - badlands-companion
      - lavavu
