name: badlands-workshop
channels:
  - conda-forge
  - fastai
dependencies:
  - python=3.8
  - jupyterlab=2.1
  - numpy=1.21
  - pip
  - pandas
  - scipy
  - compilers
  - gfortran
  # - scikit-image
  # - scikit-learn=0.23
  - h5py
  - cmocean
  # - shapely
  # - cartopy
  # - pillow
  # - descartes
  - pyvista
  - meshplex
  - pip:
      - matplotlib==3.3.4
      - gFlex
      - plotly
      - badlands
      # - badlands-companion
      - lavavu
      - piglet
      - pyvirtualdisplay
