name: badlands-workshop
channels:
  - conda-forge
  - fastai
  - geo-down-under
dependencies:
  - python=3.7
  - jupyterlab=2.1
  - numpy=1.21
  - pip
  - pandas
  - scipy
  - compilers
  - gfortran
  - h5py
  - cmocean
  - meshplex
  - gFlex
  - pyvirtualdisplay
  - colorlover
  - plotly
  - lavavu
  - pip:
      # - matplotlib==3.3.4
      # - gFlex
      # - colorlover
      - badlands
      # - lavavu
      # - piglet
      # - pyvirtualdisplay
      # - plotly
